version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    ports:
      - "8000:8000"
#    volumes:
 #     - .:/var/www
    depends_on:
      - mysql
    env_file:
      - .env  # Load environment variables from the .env file

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dca_project
      MYSQL_ROOT_PASSWORD: root@7865
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
