name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install expect
      run: sudo apt-get install -y expect

    - name: SSH into server and run commands using password
      run: |
        expect <<EOF
        set timeout -1
        spawn ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }}
        expect "password:"
        send "${{ secrets.SSH_PASSWORD }}\r"
        expect "#"
        send "cd /root/DCA_project\r"
        expect "#"
        send "git pull origin main\r"
        expect "#"
        send "docker compose build app\r"
        expect "#"
        send "docker compose up app -d\r"
        expect "#"
        send "exit\r"
        EOF
